version: "3.4"
services:
  zookeeper:
    image: bitnami/zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka:
    image: bitnami/kafka
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
#      KAFKA_BROKER_ID: 1
#      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
#      ALLOW_PLAINTEXT_LISTENER: yes
    depends_on:
      - zookeeper

  cli:
    image: bitnami/kafka
    hostname: cli
    container_name: cli
    depends_on:
      - kafka
    entrypoint: /bin/sh
    tty: true

  mariadb:
    container_name: mariadb_job
    hostname: mariadb
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: jobP@sswOrd
      MYSQL_DATABASE: js7db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      - --skip-character-set-client-handshake
    networks:
      - js7network
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_business
    restart: unless-stopped
    ports:
      - "8180:80"
    environment:
      PMA_HOST: mariadb
      PMA_VERBOSE: business
      PMA_PORT: 3306
    depends_on:
      - mariadb


volumes:
  zookeeper_data:
    driver: local

  kafka_data:
    driver: local

  mariadb:
    driver: local
#    driver_opts:
#      type: none
#      device: ${PWD}/db_data
#      o: bind

